version: '3'
services:
  golang:
    build:
      context: ./docker
      dockerfile: golang.docker
    volumes:
      - ".:/go"
    ports:
      - "8081:8080"
    tty: true

  mysql:
    build:
      context: ./docker
      dockerfile: mysql.docker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hh
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: hh_db
    ports:
      - "3307:3306"
    volumes:
      - ./var/mysql/data:/var/lib/mysql
    tty: true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    tty: true

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - "5601:5601"
    tty: true